// Code generated by goctl. DO NOT EDIT.
package types

type AuthResp struct {
	Token string `json:"token"`
}

type RecommendReq struct {
	Limit  int64  `form:"limit"`
	Cursor string `form:"cursor,optional"`
}

type RecommendListResp struct {
	Cursor string          `json:"cursor"`
	List   []RecommendUser `json:"list"`
}

type RecommendUser struct {
	UxuyId          string `json:"uxuyId"`
	Name            string `json:"name"`
	Avatar          string `json:"avatar"`
	RecommendReason string `json:"recommendReason"`
}

type UserInfoReq struct {
	Address string `form:"address"`
}

type UserInfoResp struct {
	UxuyId    string `json:"uxuyId"`
	Name      string `json:"name"`
	Avatar    string `json:"avatar"`
	Did       string `json:"did"`
	CreatedAt string `json:"createdAt"`
}

type AddressReq struct {
	Did string `form:"did"`
}

type AddressResp struct {
	Address string `json:"address"`
}

type NameReq struct {
	Address string `form:"address"`
}

type NameResp struct {
	Did string `json:"did"`
}

type UserMpcKeyReq struct {
	Address string `form:"address"`
}

type UserMpcKeyResp struct {
	MpcKey string `json:"mpcKey"`
}
