// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	interfa "uxuy/src/internal/handler/interfa"
	"uxuy/src/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.ApiKey},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/auth",
					Handler: interfa.AuthHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.ApiKey},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/recommend",
					Handler: interfa.RecommendHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/userInfo",
					Handler: interfa.UserInfoHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/getAddress",
					Handler: interfa.GetAddressHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/getName",
					Handler: interfa.GetNameHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/getUserMpcKey",
					Handler: interfa.UserMpcKeyHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)
}
